config/routes.rb
Rails.application.routes.draw do
  root 'homes#index'
  devise_for :users

  resources :workshops, except: :delete do
    resources :registrations
  end
end

app/models/registration.rb
class Registration < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  belongs_to :user
  belongs_to :workshop

  def my_registration(current_workshop)
    current_user.registrations.find_by(workshop: current_workshop)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  mount_uploader :profile_photo, ProfilePhotoUploader

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :workshops
  has_many :registrations
end

app/models/workshop.rb
class Workshop < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  mount_uploader :workshop_pic, WorkshopPicUploader
  belongs_to :user
  has_many :registrations
  has_many :users, through: :registrations

  validates :name, presence: true
  validates :description, presence: true
  validates :date, presence: true
  validate :date_is_in_the_future, on: :create
  validates :street, presence: true
  validates :city, presence: true
  validates :state, presence: true
  validates :zip, presence: true
  validates :user_id, presence: true

  def date_is_in_the_future
    errors.add(:date, "must be in the future") if (date < DateTime.now)
  end

  def formatted_date
    date.strftime("%B %d, %Y at %H:%M")
  end

  def self.search(search)
    @workshops = Workshop.where('name ILIKE ?', "%#{search}%")
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :profile_photo
    devise_parameter_sanitizer.for(:account_update) << :profile_photo
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create]

  def create
    @registration = Registration.new(:workshop_id => params[:workshop_id])
    @registration.user = current_user
    if @registration.save
      flash[:notice] = "Successfully registered!"
      redirect_to workshop_path(@registration.workshop)
    else
      render "workshops/show"
    end
  end

  def destroy
    @registration = Registration.find(params[:id])
    @registration.destroy
    flash[:notice]= "You are no longer registered for that class"
    redirect_to workshop_path(params[:workshop_id])
  end
end

app/controllers/workshops_controller.rb
class WorkshopsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update]
  def new
    @workshop = Workshop.new()
  end

  def create
    @workshop = current_user.workshops.build(workshop_params)
    if @workshop.save
      flash[:notice] = "Successfully added your workshop!"
      redirect_to workshop_path(@workshop)
    else
      render :new
    end
  end

  def show
    @workshop = Workshop.find(params[:id])
    @registration = Registration.new()
  end

  def index
    if params[:search]
      @workshops = Workshop.search(params[:search])
    else
      @workshops = Workshop.all
    end
  end

  def edit
    @workshop = current_user.workshops.find(params[:id])
  end

  def update
    @workshop = current_user.workshops.find(params[:id])
    if @workshop.update(workshop_params)
      flash[:notice] = "Successfully updated your workshop!"
      redirect_to workshop_path(@workshop)
    else
      render "edit"
    end
  end

  private

  def workshop_params
    params.require(:workshop).permit(:name, :description, :date, :street, :city, :state, :zip, :workshop_pic)
  end

end

app/views/homes/index.html.erb
<!--main row -->
<div class="row headerImage">
	<%= image_tag("map.jpg", class: "small-centered column headerImage") %>

	<div class="classContent column large-6">
	<h1 id="mainHeader">Imaginary Map Making</h1>
	<p>“My intricate pen and watercolor drawings are inspired by the visual language of maps, as well as the fractal similarity that cities share with biological processes such as the patterns of cells and neurons. I invent each place as I draw, thinking about clustering of neighborhoods, patterns of roads and the individual selective memory that an inhabitant would use to navigate their city. The physical materials also influence each work; the topography of watercolor paper, the force of gravity on ink, or the tensile limitations of paper all structure my drawings in the same way that a landscape influences urban growth.”

In this class, participants (artistic and otherwise—everyone is welcome!) will be encouraged to explore ideas of line and composition through the lens of cartography. Participants will learn techniques to organically “grow” map-like drawings from the shapes of familiar places, from stylized land forms, or completely from their own imagination.</p>
<button class="large-centered">Sign Up</button>

</div>

<div class="teacherContent column large-6">
	<h2>Emily Garfield</h2>
<p>Emily Garfield creates intricate maps of imaginary places that explore the origins of cities and the function of maps themselves. She received her BA in Visual Arts from Brown University, where she also pursued studies in the brain’s response to art and aesthetic beauty through the Cognitive Science department. She has participated in exhibitions throughout the greater Boston area as well as New York and Philadelphia. Her work is in the collection of the Kamm Teapot Foundation as well as numerous private collections.</p>

</div>
</div>



<div class="socialMediaButtons">
	<a href=""><%= image_tag("facebook-icon.png")%></a>
</div>
<div class="socialMediaButtons">
	<a href=""><%= image_tag("twitter-icon.png")%></a>
</div>
<div class="socialMediaButtons">
	<a href=""><%= image_tag("email-icon.png")%></a>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SkillshareSomerville</title>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= csrf_meta_tags %>
</head>
<body>

  <nav class="top-bar">
    <ul class="title-area">
      <li class="name">
        <h1><a href="/">SkillshareSomerville</a></h1>
      </li>
    </ul>

    <section class="top-bar-section">
      <ul class="right">
        <li class="has-form">
          <div class="row collapse">
            <div class="large-8 small-9 columns">
              <%= form_tag workshops_path, :method => 'get' do %>
              <%= text_field_tag :search, params[:search] %></div>
              <div class="large-4 small-3 columns">
                <%= submit_tag "Search", :class =>"alert button expand" %>
                <% end %>
              </div>
            </div>
          </li>
        <li><%= link_to "Browse workshops", workshops_path %></li>
        <li class="divider"></li>
        <li><%= link_to "Add a workshop", new_workshop_path %></li>
        <li class="divider"></li>
        <%- if current_user -%>
        <li><img src="<%= current_user.profile_photo %>" width="30" height="30"></li>
        <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
        <li class="divider"></li>
        <li><%= link_to 'Edit Profile', edit_user_registration_path(@user)%></li>
        <%- else -%>
        <li><%= link_to 'Sign Up', new_user_registration_path%></li>
        <li class="divider"></li>
        <li><%= link_to 'Sign In', new_user_session_path %></li>
        <%- end -%>
      </ul>
    </section>
  </nav>

  <%- flash.each do |key, value| -%>
    <div class="row">
      <div class="small-12 alert-box alert">
        <div class="flash flash-<%= key %>">
          <%= value %>
        </div>
      </div>
    </div>
  <%- end -%>

  <%= yield %>

  <%= javascript_include_tag 'application' %>
  <%= javascript_tag do %>
    $(function(){
      $(document).foundation();
    });
  <% end %>
  <%= yield :extra_footer %>
</body>
</html>

app/views/workshops/_form.html.erb
<% if @workshop.errors.any? %>
  <% @workshop.errors.full_messages.each do |msg| %>
    <%= msg %>
  <% end %>
<% end %>

<%= form_for @workshop do |f| %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name, autofocus: true %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description, autofocus: true %>
  </div>
  <div class="field">
    <%= f.label :date %><br />
    <%= f.datetime_select :date, start_year: Date.today.year %>
  </div>
  <div class="field">
    <%= f.label :street, "Street address" %><br />
    <%= f.text_field :street, autofocus: true %>
  </div>
  <div class="field">
    <%= f.label :city %><br />
    <%= f.text_field :city, autofocus: true %>
  </div>
  <div class="field">
    <%= f.label :state %><br />
    <%= f.text_field :state, autofocus: true %>
  </div>
  <div class="field">
    <%= f.label :zip, "Zip code" %><br />
    <%= f.text_field :zip, autofocus: true %>
  </div>
  <div class="field">
    <%= f.label :workshop_pic, "Photo" %><br />
    <%= f.file_field :workshop_pic %>
  </div>
  <div class="row newUserSubmit">

      <%= f.submit class: "small-centered column button" %>  

  </div
<% end %>

app/views/workshops/edit.html.erb
<%= render "form" %>

app/views/workshops/index.html.erb
    <div class="row">
      <div class="large-4 small-12 columns">
        <%= image_tag("somervilleskillsharelogo.png") %>
        <div class="hide-for-small panel">
          <h3>Somerville Skillshare</h3>
          <h5 class="subheader">40 free classes in 6 hours. Organized and taught by local residents. March 2nd, 2014 at the Somerville Armory.
          </h5>
        </div>
      </div>

      <div class="large-8 columns">
        <div class="row">
          <% @workshops.each do |workshop| %>
            <div class="large-4 small-6 columns">
              <%= image_tag(workshop.workshop_pic.url) %>

              <div class="panel">
                <h5><%= link_to(workshop.name, workshop_path(workshop)) %></h5>
                <h6 class="subheader"><%= workshop.description %></h6>
              </div>
            </div>
          <% end %>
        </div>
      </div>

app/views/workshops/new.html.erb
<div class="row">
	<div class="column small-12 medium-8 large-8 medium-centerd large-centered">
	<h1>Add a Workshop</h1>
		<%= render "form" %>		
	</div>
</div>

app/views/workshops/show.html.erb
<% if @registration.errors.any? %>
  <% @registration.errors.full_messages.each do |msg| %>
    <%= msg %>
  <% end %>
<%end%>

Registered users:
<% @workshop.registrations.each do |registration|%>
  <div class="panel">
    <%= registration.user.email %>
  </div>
<%end%>

<div class="bigBackground">
  <div class="row">
  <div class="column small-12 medium-8 large-6 medium-centered large-centered whiteBackground">
   <span id="workshopName"> <%= @workshop.name %><br> </span>
<%= @workshop.description %><br>
<%= @workshop.date %><br>
<%= @workshop.street %><br>
<%= @workshop.city %><br>
<%= @workshop.state %><br>
<%= @workshop.zip %><br>
<%= image_tag @workshop.workshop_pic.url %>

    <% if signed_in? %>
      <%if current_user.registrations.where(workshop: @workshop).empty? %>
        <div>
          <%= form_for [@workshop, @registration] do |f| %>
            <%= f.submit "Register", class: "button" %>
          <% end %>
        </div>
      <%else%>
      <% registration = current_user.registrations.find_by(workshop: @workshop)%>
        <div>
          <%= link_to "Delete my registration", [@workshop, registration], method: :delete, data: { confirm: "Are you sure you want to remove your registration?"}, class: "button" %>
        </div>
      <% end %>
      <% if current_user == @workshop.user %>
        <div>
          <%= link_to "Edit Workshop", edit_workshop_path(@workshop), class: "button" %>
        </div>
      <% end %>
    <% end %>
  </div>
</div>